### ISSUE TITLE
Add the content param to index

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/elasticlunr-search-widget#19]
At the moment the index works only with the preview. Let's add also the content param.

**Comment by amihaiemil** [comment]
https://humanwhocodes.com/blog/2019/04/jekyll-hooks-output-markdown/

**Comment by amihaiemil** [comment]
done

**Comment by amihaiemil** [comment]
@rultor release it, tag is `0.0.3`

**Comment by amihaiemil** [comment]
@rultor hello

**Comment by amihaiemil** [comment]
done

**Comment by atefaz** [comment]
gRPC
