### ISSUE TITLE
0.0.4: Offer Dark Theme

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/elasticlunr-search-widget#21]
Right now the widget is white + blue/grey text. We should also offer the possibility to switch to a Dark Theme.

Basically we need to copy/paste the existing CSS and change the color scheme to a dark pallette. 

The user should switch it via the ``theme`` parameter:

```java
<script
    type="text/javascript"
    id = "elnr-sw-script"
    theme="dark"              <!--Optional, defaults to the classic light theme-->
    size="3"                       <!--Optional, defaults to 3-->
    placeholder="Enter keywords"   <!--Optional, defaults to "Enter keywords..."-->
    src="https://amihaiemil.com/js/elasticlunr/elasticlunr-search-widget.min.js"> <!--Latest ElasticLunr search widget-->
</script>
```

Based on this flag, inside [elasticlunr-search-widget.js](https://github.com/amihaiemil/elasticlunr-search-widget/blob/master/src/js/elasticlunr-search-widget.js#L21) we should decide which CSS to append to the page.

Want to fix this Issue and get the Bounty cash? Read [this](https://amihaiemil.com/2020/02/15/solve-github-issues-and-get-cash.html) first!

**Comment by arpitkalla** [comment]
Hey, I am interested in working on this!

**Comment by amihaiemil** [comment]
@arpitkalla sure, go ahead :)

**Comment by arpitkalla** [comment]
Added PR #25

**Comment by amihaiemil** [comment]
@arpitkalla nice. Please, send me your PayPal email address.

**Comment by arpitkalla** [comment]
> @arpitkalla nice. Please, send me your PayPal email address.

Emailed it to you. Thanks!

**Comment by amihaiemil** [comment]
Paid with transaction id: 5VN942706K8387036

**Comment by amihaiemil** [comment]
@rultor release it, tag is `0.0.4`

**Comment by amihaiemil** [comment]
@arpitkalla thanks!
